mysql:
  host: 'localhost:3306'
  user: root
  password: 123456
  database: root

cart-table:
  table-name: diverse_cart
  username: username
  title: title
  iid: iid
  extra: extra
  type: type
  amount: amount
  server-id: server_id
server-id: 1

split-symbol: '<:>'